version: '3.4'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "5433:1433"
    volumes:
      - restaurant-sqldata:/var/opt/mssql
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status"]
      interval: 5s
      timeout: 20s
      retries: 5
  orders.api:
    image: localhost:5000/ordersapi
    environment:
      - ASPNETCORE_URLS=http://+:80
    depends_on:
      rabbitmq:
        condition: service_healthy
    build:
      context: ./
      dockerfile: ./src/services/Orders/Orders.API/Dockerfile
volumes:
  restaurant-sqldata: